apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

resources:
- vendor/nginx-ingress.yaml

patches: # Usage: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
- path: service.yaml

images: # Import: az acr import -n acrciamdevuan5o5ufr --source docker.io/nginx/nginx-ingress:3.6.1
- name: nginx/nginx-ingress
  newName: acrciamdevuanc67lyf.azurecr.io/nginx/nginx-ingress
  newTag: 3.6.1
