apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi
  volumeName: azurefile
  resources:
    requests:
      storage: 20Gi