# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pingfederate-secrets-provider-class
spec:
  provider: azure
  secretObjects:
    - secretName: pingfederate-svc-acc-passwords
      type: Opaque
      data:
        - key: PING_IDENTITY_PASSWORD                  # see note 1 & 8
          objectName: pingfed-admin-password           # see note 2
          
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "3e0a8435-b060-45ed-a4d6-dc385a686473"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "pingdevops-az-vault"       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: pingfed-admin-password
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: pingfederate-license
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          
    tenantId: "6e26baa3-bf93-4bf7-85ae-9111969cd7cc"                # The tenant ID of the key vault